# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  # An example config option to customise the log level of the workload
  log-level:
    description: |
      Configures the log level of gunicorn. 

      Acceptable values are: "info", "debug", "warning", "error" and "critical"
    default: "info"
    type: string
  kube-state-metrics-namespace:
    description: |
      The namespace where kube-state-metrics is deployed. Volcano scheduler will
      use this to define the scrape job for Prometheus.
    default: "kube-system"
    type: string