#!/bin/bash

usage() { echo "Usage $0 [-n name] -o output_path -c channel" 1>&2; exit 1; }

while getopts "n:o:c:" arg; do
    case "${arg}" in
        n)
            name=${OPTARG}
            ;;
        o)
            output=${OPTARG}
            ;;
        c)
            channel=${OPTARG}
            ;;
        *)
            echo "broke ${arg} - ${OPTARG}"
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${name}" ] || [ -z "${output}" ] || [ -z "${channel}" ]; then
    usage
fi

echo "Bundle      = '${name}'"
echo "Output Path = '${output}'"
echo "Channel     = '${channel}'"

mkdir -p "${output}"
for f in ./.bundle_template/*; do
    CHANNEL=$channel envsubst < "${f}" > ${output}/$(basename ${f})
done
