{
 "title": "Volcano Global Overview Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "TPH –Schedule Task In 1 Hour",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(max_over_time(kube_pod_container_status_running{job=~\".+kube-state-metrics\"}[1h]) != 0)"
    }
   ]
  },
  {
   "title": "Volcano Node",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_info{job=~\".+kube-state-metrics\"})"
    }
   ]
  },
  {
   "title": "Volcano GPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_capacity{resource=\"nvidia_com_gpu\",job=~\".+kube-state-metrics\"}"
    }
   ]
  },
  {
   "title": "Volcano Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{job=~\".+kube-state-metrics\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Volcano CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{job=~\".+kube-state-metrics\", resource=\"cpu\"})"
    }
   ]
  },
  {
   "title": "Volcano Legency Heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(volcano_e2e_job_scheduling_latency_milliseconds_bucket[1h])",
     "legendFormat": "\\{\\{le\\}\\} ms"
    }
   ]
  },
  {
   "title": "Volcano Job Scheduling Avg Duration By Queue In 24H",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(volcano_e2e_job_scheduling_duration{}) by (queue)",
     "legendFormat": "\\{\\{queue\\}\\}"
    }
   ]
  },
  {
   "title": "Volcano Job Avg Scheduling Duration By Namespace In 24H",
   "type": "table",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(volcano_e2e_job_scheduling_duration{}) by (job_namespace)",
     "legendFormat": "Namespace: \\{\\{job_namespace\\}\\}"
    }
   ]
  },
  {
   "title": "Volcano Resource Usage Sort By Queue In 24H",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(kube_pod_volcano_container_resource_requests{resource=\"memory\", unit=\"byte\",job=~\".+kube-state-metrics\",queue!=\"\"}) by (queue)",
     "legendFormat": "\\{\\{queue\\}\\}"
    }
   ]
  },
  {
   "title": "Volcano Resource Usage Sort By Namespace In 24H",
   "type": "table",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_pod_volcano_container_resource_requests{resource=\"memory\", unit=\"byte\",job=~\".+kube-state-metrics\"}) by (volcano_namespace)",
     "legendFormat": "Namespace : \\{\\{volcano_namespace\\}\\}"
    }
   ]
  },
  {
   "title": "Volcano Job Running Legency",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "increase(volcano_e2e_job_scheduling_duration{}[24h]) != 0"
    }
   ]
  },
  { "title": "Volcano Fairness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Job Duration Coefficient Of Variation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "stddev(volcano_e2e_job_scheduling_duration)/avg(volcano_e2e_job_scheduling_duration)",
     "legendFormat": "CV (Job Duration)"
    }
   ]
  },
  { "title": "Volcano Effectiveness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Volcano Cluster Average CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 65 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(\n(sum(kube_pod_container_resource_requests{resource=\"cpu\"}) by (pod,namespace)) * on(pod) (max(kube_pod_container_status_running{}) \nby (pod,namespace)))/\nsum(kube_node_status_allocatable{resource=\"cpu\", unit=\"core\"})"
    }
   ]
  },
  {
   "title": "Volcano Cluster Average Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 65 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"memory\"}) by (pod,namespace)) * on(pod) (max(kube_pod_container_status_running{}) by (pod,namespace)))/sum(kube_node_status_allocatable{resource=\"memory\", unit=\"byte\"})"
    }
   ]
  },
  {
   "title": "Volcano Cluster Average GPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 65 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum((sum(kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}) by (pod,namespace)) * on(pod) (max(kube_pod_container_status_running{}) by (pod,namespace)))/sum(kube_node_status_capacity{resource=\"nvidia_com_gpu\"})"
    }
   ]
  },
  {
   "title": "Node Resource Coefficient Of Variation",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "stddev(sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\"}))/avg(sum by (node) (kube_pod_container_resource_requests{resource=\"cpu\"}))",
     "legendFormat": "CV (CPU)"
    },
    {
     "expr": "stddev(sum by (node) (kube_pod_container_resource_requests{resource=\"memory\"}))/avg(sum by (node) (kube_pod_container_resource_requests{resource=\"memory\"}))",
     "legendFormat": "CV (Memory)"
    },
    {
     "expr": "stddev(sum by (node) (kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}))/avg(sum by (node) (kube_pod_container_resource_requests{resource=\"nvidia_com_gpu\"}))",
     "legendFormat": "CV (Nvidia GPU)"
    }
   ]
  }
 ]
}